Project/ProjectSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePageViewIndex

urlpatterns = [
    path('dashboard/', include('console_admin.urls', namespace='admin')),
    path('auth/', include('authentication.urls')),
    path('folio/', include('portfolio.urls')),
    path('', HomePageViewIndex.as_view(), name='index'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Project/authentication/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


app_name = 'authentication'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('account/', views.AccountView.as_view(), name='account'),
    path('account/infos/', views.InfoCustomer.as_view(), name='information'),

]

Project/console_admin/urls.py
from django.urls import path
from .views import customer, parameters,product, portfolio
from order.views import (HomepageView, OrderUpdateView, CreateOrderView, delete_order,
                         done_order_view, OrderUpdateHeader,
                         add_product, modify_order_item,  order_action_view
                         )

app_name = 'console_admin'
urlpatterns = [
    path('', HomepageView.as_view(), name='console_admin'),

    # Customers
    path('list_customer', customer.list_customer, name='list_customer'),
    path('create_customer/', customer.customer, name="create_customer"),
    path('update_customer/<str:pk>/', customer.customer, name="update_customer"),
    path('delete_customer/<str:pk>/', customer.delete_customer,
         name="delete_customer"),

    # Parameters
    path('list_parameters/', parameters.list_parameters, name="list_parameters"),
    path('create_parameters/', parameters.parameters, name="create_parameters"),
    path('update_parameters/<str:pk>/', parameters.parameters, name="update_parameters"),
    path('delete_parameters/<str:pk>/', parameters.delete_parameters, name="delete_parameters"),


    # Portfolio
    path('list_portfolio/', portfolio.list_portfolio, name="list_portfolio"),
    path('create_portfolio/', portfolio.create_portfolio, name="create_portfolio"),
    path('update_portfolio/<str:pk>/', portfolio.update_portfolio,
         name="update_portfolio"),
    path('delete_portfolio/<str:pk>/', portfolio.delete_portfolio,
         name="delete_portfolio"),

    # Category
    path('categories-list/', product.CategoriesListView.as_view(), name='categories_list'),
    path('categories-create/', product.CreateCategoriesView.as_view(), name='categories_create'),
    path('categories-update/<int:pk>/', product.CategoryUpdateView.as_view(), name='categories_update'),
    path('categories-delete/<int:pk>/', product.delete_category, name='categories_delete'),

    # Product
    path('product-list/', product.ProductListView.as_view(), name='product_list'),
    path('product-create/', product.CreateProductView.as_view(), name='product_create'),
    path('product-update/<int:pk>/', product.ProductUpdateView.as_view(), name='product_update'),
    path('product-delete/<int:pk>/', product.delete_product, name='product_delete'),

    # order
    path('create/', CreateOrderView.as_view(), name='create_order'),
    path('update-order/<int:pk>/', OrderUpdateHeader.as_view(), name='update_order_header'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='update_order'),
    path('done/<int:pk>/', done_order_view, name='done_order'),
    path('delete/<int:pk>/', delete_order, name='delete_order'),
    path('action/<int:pk>/<slug:action>/', order_action_view, name='order_action'),
    path('add-product/<int:pk>/<int:dk>/',add_product, name='add_product'),
    path('modify-order-item/<int:orderid>/<int:pk>/<slug:action>', modify_order_item, name='modify_order_item'),

]

Project/portfolio/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


app_name = 'portfolio'
urlpatterns = [
    path('all/', views.allportfolio,name='all'),
    path("detail/<int:pk>/", views.detailportfolio,name='detail'),
]

Project/templates/base.html
<!DOCTYPE html>
<html lang="fr">

<head>
  {% load static %}

        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Sandrine Chevalier</title>
        <!-- Plugins CSS -->
        <link href="{% static 'css/plugins/plugins.css' %}" rel="stylesheet">
        <!-- load css for cubeportfolio -->
        <link rel="stylesheet" type="text/css" href="{% static 'cubeportfolio/css/cubeportfolio.min.css' %}">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>

</head>

        <!-- Site Overlay -->
        <div class="site-overlay"></div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-transparent navbar--darkimg">
            <div class="container">
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">
                    {% if logo.url != '' %}
                        <img  class="logo logo-light hidden-md-down" src="{{logo.url}}" >
                    {% else %}
                        Pas de logo enregistré
                    {% endif %}
                    {{tel_societe}}

                </a>

                <div  id="navbarNavDropdown" class="navbar-collapse collapse">

                    <ul class="navbar-nav ml-auto ">

                        <li class="nav-item dropdown"><a href="{% url 'index' %}" class="nav-link">Accueil</a></li>
                        <li class="nav-item dropdown"><a href="{% url 'portfolio:all' %}" class="nav-link">Portfolio</a></li>


                    {% if user.is_authenticated %}
                         <ul class="nav-item dropdown">
                         {% if user.is_staff %}
                             <a class="nav-link  dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">Espace Admin</a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="{% url 'console_admin:console_admin' %}" class="btn btn-outline-primary mb-2">Administrateur</a></li>
                                    <li><a href="{% url 'authentication:logout' %}" class="dropdown1-item">Se Déconnecter</a></li>
                                </ul>

                         {% else %}
                             <a class="nav-link  dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">Mon espace</a>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a href="{% url 'authentication:account' %}" class="dropdown-item">Acces à mon espace client</a></li>

                                    <li><a href="{% url 'authentication:logout' %}" class="dropdown1-item">Se Déconnecter</a></li>
                                </ul>
                         {% endif %}
                    {% else %}
                         <li class="nav-item"><a href="{% url 'authentication:login' %}" class=" btn btn-primary btn-rounded btn-sm">Se Connecter</a></li>
                    {% endif %}
                        </ul>
                </div>

                </ul>
            </div>
        </nav>
  {% block content %}
  
  {% endblock %}


  <!-- Footer -->
 <footer id="footer" class="footer footer-dark pt50 pb10">
            <div class="container">
                <div class="info-footer">
                    <div class="col-lg-3 col-md-6 mb40">
                        <h3>A propos de moi</h3>
                        <p>
                            {{ propos_moi}}
                        </p>
                        <a href="#" class="btn btn-sm btn-white-outline">Learn More</a>
                    </div>
                    <div class="col-lg-3 col-md-6 mb40">
                        <h3>A suivre</h3>
                        <ul class="list-unstyled footer-list-item">
                            <li>
                                <a href="#">
                                    Lorem ipsum dolor sit amet
                                </a><br>
                                <em>10 Octobre 2020</em>
                            </li>
                            <li>
                                <a href="#">
                                    Consectetur adipiscing elit
                                </a><br>
                                <em>12 Octobre 2020</em>
                            </li>
                            <li>
                                <a href="#">
                                    Sed do eiusmod tempor incididunt
                                </a><br>
                                <em>15 Octobre 2020</em>
                            </li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 mb40">
                        <h3>Me Contacter</h3>
                        <ul class="list-unstyled contact-list-item">
                            <li>
                                <i class="ti-home"></i>
                                {{nom_societe}} {{ adresse_societe }}
                            </li>
                            <li>
                                <i class="ti-email"></i>
                                {{email_societe}}
                            </li>
                            <li>
                                <i class="ti-mobile"></i>
                              {{tel_societe}}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="bottom-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-4">
                            <span>&copy; Copyright 2020. Tous droits réservés.</span>
                        </div>
                        <div class="col-sm-8 text-right">
                            <ul class="list-inline footer-nav">
                                <li class="list-inline-item">
                                    <a href="#">Accueil</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
<!--/footer-->
  <a href="#" class="back-to-top hidden-xs-down" id="back-to-top"><i class="ti-angle-up"></i></a>
        <!-- jQuery first, then Tether, then Bootstrap JS. -->
        <script type="text/javascript" src="{% static 'js/plugins/plugins.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/assan.custom.js' %}"></script>
        <!-- load cubeportfolio -->
        <script type="text/javascript" src="{% static 'cubeportfolio/js/jquery.cubeportfolio.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/cube-mosaic.js' %}"></script>

</body>

</html>

Project/templates/baseadmin.html
<!DOCTYPE html>
<html lang="fr">
    <head>
    {% load render_table from django_tables2 %}
    {% load static %}

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Dashboard</title>
    <!-- Bootstrap-->
    <link href="{% static 'lib/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!--Common Plugins CSS -->
    <link href="{% static 'cssadmin/plugins/plugins2.css' %}" rel="stylesheet">
    <!--fonts-->
    <link href="{% static 'lib/line-icons/line-icons.css' %}" rel="stylesheet">
    <link href="{% static 'lib/font-awesome/css/fontawesome-all.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/dt-picker/jquery.datetimepicker.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/select2/dist/css/select2.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/chartist/chartist.min.css' %}" rel="stylesheet" />
    <link href="{% static 'cssadmin/chartist-custom.css' %}" rel="stylesheet" />
    <link href="{% static 'cssadmin/picker-custom.css' %}" rel="stylesheet" />
    <link href="{% static 'cssadmin/select2-custom.css' %}" rel="stylesheet">
    <link href="{% static 'cssadmin/style.css' %}" rel="stylesheet">
</head>
<body class="bg-white">
    <div class="page-wrapper" id="page-wrapper">
    <aside id="page-aside" class=" page-aside">
        <div class="sidenav darkNav">
            <a href="{% url 'console_admin:console_admin' %}" class="app-logo d-flex flex flex-row align-items-center overflow-hidden justify-content-center">
                <span class="nav-text"> S a n d r i n e - C h e v a l i e r</span>
            </a>
            <div class="flex">
                <div class="aside-content">
                    <p> </p>
                    <p class="nav-text text-center">
                        <a href="{% url 'console_admin:console_admin' %}" class="btn btn-icon btn-outline-info mb-2 ">
                            <i class="icon-Administrator"></i> Dashboard Accueil
                        </a>
                    </p>
                    <p class="nav-text text-center">
                        <b>A D M I N I S T R A T I O N</b>

                    </p>
                    <ul class="metisMenu" id="metisMenu">
                        <li >
                            <i class="icon-Folder nav-thumbnail"></i>
                            <a class="has-arrow" href="{% url 'console_admin:categories_list' %}">
                                <span class="nav-text">
                                    Categories
                                </span>
                            </a>
                        </li>
                        <li > <i class="icon-Apple nav-thumbnail"></i>
                            <a class="has-arrow" href="{% url 'console_admin:product_list' %}">
                                <span class="nav-text">
                                    Produits
                                </span>
                            </a>
                        </li>

                        <li >
                            <i class="icon-Face-Style nav-thumbnail"></i>
                            <a class="has-arrow" href="{% url 'console_admin:list_customer' %}">
                                <span class="nav-text">
                                    Client
                                </span>
                            </a>
                        </li>
                        <li > <i class="icon-Add-Basket nav-thumbnail"></i>
                            <a class="has-arrow" href="{% url 'admin:console_admin' %}">
                                <span class="nav-text">
                                    Commande
                                </span>
                            </a>
                        </li>
                        <!--Menu-Portfolio-->
                        <li > <i class="icon-Picasa nav-thumbnail"></i>
                            <a class="has-arrow" href="{% url 'console_admin:list_portfolio' %}">
                                <span class="nav-text">
                                    Portfolio
                                </span>
                            </a>
                        </li>
                        <!--Menu Parametre-->
                        <li > <i class="icon-Save nav-thumbnail"></i>
                            <a class="has-arrow" href="{% url 'console_admin:list_parameters' %}">
                                <span class="nav-text">
                                    Paramètrage
                                </span>
                            </a>
                        </li>
                    </ul>
                </div><!-- aside content end-->
                <a href="{% url 'authentication:logout' %}" >
                    <p class="nav-text bg-danger text-center">
                        <b> >>> Se Déconnecter <<<</b>
                    </p>
                </a>
            </div><!-- aside hidden scroll end-->
            <div class="aside-footer p-3 pl-25">
                <div class="text-center ">
                    App Version - 1.0
                </div>
            </div><!-- aside footer end-->
        </div><!-- sidenav end-->
    </aside><!-- page-aside end-->
    <main class="content">
        <header class="navbar page-header darkHeader navbar-expand-lg">
            <ul class="nav flex-row order-lg-1 ml-auto nav-icons">
                <ul class="nav flex-row order-lg-2 ml-auto nav-icons">
                    <a href="{% url 'index' %}" class="btn btn-icon btn-outline-pink mb-2 ">
                        <i class="icon-Face-Style2"></i>Site Client
                    </a>
                </ul>
            </ul>
        </header>
        {% block content %}
        {% endblock %}
        <footer class="content-footer bg-dark b-t">
            <div class="d-flex flex align-items-center pl-15 pr-15">
                <div class="d-flex flex p-3 ml-auto">
                    <div>
                        <a href="mailto:gregory.leterte@gmail.com" class="d-inline-flex pl-0 pr-2 b-r"> <span class="text-dark  ml-1 ">Grégory Le Terte >> Contacter développeur << </span></a>
                    </div>
                </div>
                <div class="d-flex flex p-3 mr-auto justify-content-end">
                    <div class="text-muted">© Copyright 2020-2021 Sandrine Chevalier</div>
                </div>
            </div>
        </footer><!-- footer end-->
    </main>
    </div>
</body>
<!-- Common plugins -->
<script type="text/javascript" src="{% static 'jsadmin/plugins/plugins.js' %}"></script>
<script type="text/javascript" src="{% static 'jsadmin/appUi-custom.js' %}"></script>
<script src="{% static 'lib/chartist/chartist.min.js' %}"></script>
<script src="{% static 'lib/chartist/chartist-tooltip.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/peity/jquery.peity.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/dt-picker/jquery.datetimepicker.full.min.js' %}"></script>
<script src="{% static 'lib/select2/dist/js/select2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'jsadmin/dashboard02-custom.js' %}"></script>

{% include 'order/include/js.html' %}
    {%  block extra_js %}{% endblock %}
</html>

Project/templates/dashboard_admin.html
{% extends 'baseadmin.html' %} {% load render_table from django_tables2 %} {% load static %}

{% block content %}
    <div class="page-content">
        <div class="container-fluid">
            <div class="row align-items-center mb-30 pt-30">
                <div class="col-md-12 mr-auto ml-auto">
                    <div class="mb-0">
                        <h4>Action rapide, vue generale </h4>
                        <!-- Widget -->
                        <div class="page-content">
                            <div class="container-fluid">
                                <div class="title-sep sep-body mb-30">

                                    <span>Chiffres</span>
                                </div>
                                <div class="row">
                                    <div class="col-lg-3 col-md-6 mb-30">
                                        <div class="list bg-white border1">
                                            <div class="list-item">
                                                <div class="list-thumb avatar si-colored-facebook  rounded avatar50">
                                                    <i class="fa fa-user-circle"></i>
                                                </div>
                                                <div class="list-body text-right">
                                                    <span class="list-title fs-1x">
                                                        <a href="{% url 'console_admin:list_customer' %}">
                                                            {{ count_customers}} client{{ count_customers|pluralize}}
                                                        </a>
                                                    </span>
                                                    <span class="list-content">Nombre Inscrits au site
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div><!--col-->
                                    <div class="col-lg-3 col-md-6 mb-30">
                                        <div class="list bg-white border1">
                                            <div class="list-item">
                                                <div class="list-thumb avatar bg-danger  rounded avatar50">
                                                    <i class="fa fa-file"></i>
                                                </div>
                                                <div class="list-body text-right">
                                                    <span class="list-title fs-1x">
                                                        <a href="{% url 'admin:console_admin'%}">
                                                            {{ quotation_count}} Devis
                                                        </a>
                                                    </span>
                                                    <span class="list-content">
                                                        <span class="fs12 d-block text-danger pt-8">
                                                            <i class="fa fa-arrow-right"></i>
                                                            <b>{{total_quotation}}</b></span>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div><!--col-->
                                    <div class="col-lg-3 col-md-6 mb-30">
                                        <div class="list bg-white border1">
                                            <div class="list-item">
                                                <div class="list-thumb avatar si-colored-twitter  rounded avatar50">
                                                    <i class="fa fa-shopping-basket"></i>
                                                </div>
                                                <div class="list-body text-right">
                                                    <span class="list-title fs-1x">
                                                        <a href="{% url 'admin:console_admin'%}">
                                                            {{ order_no_is_paid_count}} Bon{{order_no_is_paid_count|pluralize}}
                                                            de commande{{order_no_is_paid_count|pluralize}}
                                                        </a>
                                                    </span>
                                                    <span class="list-content">
                                                        <span class="fs12 d-block text-warning  pt-8">
                                                            <i class="fa fa-arrow-right " style="color:#0055ff;">
                                                                <b>{{ total_order_no_is_paid}}</b></i></span>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-6 mb-30">
                                        <div class="list bg-white border1">
                                            <div class="list-item">
                                                <div class="list-thumb avatar bg-success  rounded avatar50">
                                                    <i class="fa fa-dollar-sign"></i>
                                                </div>
                                                <div class="list-body text-right">
                                                    <span class="list-title fs-1x">
                                                        <a href="{% url 'admin:console_admin'%}">
                                                            {{ order_is_paid_count}} Facture{{order_is_paid_count|pluralize}}
                                                        </a></span>
                                                    <span class="list-content">
                                                        <span class="fs12 d-block pt-8">
                                                            <i class="fa fa-arrow-right" style="color:#23440b;">
                                                                <b> {{ paid_value}} </b></i></span>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div><!--col-->
                                </div><!--row-->
                            </div>
                        </div>
                        <div class="container-fluid">
                            <div class="row">
                                <div class="col-md-6 col-lg-3">
                                    <div class="btn btn-primary">
                                        <a href="{% url 'console_admin:create_order'%}">
                                            <div class="box bg-cyan text-center">
                                                <h1 class="font-light text-white"><i class="mdi mdi-view-dashboard"></i></h1>
                                                <h6 class="text-white">Ajouter une commande</h6>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card">
                                        <div class="card-body">
                                            <h4 class="card-title">Derniere Commande, Panier Moyen des commandes : {{ average_order}}</h4>
                                        </div>
                                        <div class="comment-widgets scrollable">
                                            {% render_table orders %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% include 'order/include/js.html' %}

Project/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}

         <div class="bg-parallax fullscreen parallax-overlay"  data-jarallax-video="https://youtu.be/HKYqGAvq0rQ" data-jarallax-original-styles="null">
            <div class="d-flex align-items-center">
                <div class="container">
                    <div class=" row">
                        <div class="col-md-10  mr-auto ml-auto text-center">
                            <div class="hero-text-style1">
                                <h1 class="mt0 mb10 text-white">{{texte_accroche}}</h1>
                                <p class="lead mb20 text-white-gray">
                                    {{texte_accroche_complement}}
                                </p>
                                <a href="#footer" class="btn btn-white-outline btn-rounded">En savoir Plus</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--hero-->

{% endblock content %}

Project/templates/legal.html
{% extends "base.html" %}

{% block content %}
  <!-- User name Section -->
  <header id="user-name" class="bg-user-name">
      <div class="container-fluid h-200">
        <div class="row h-100 align-items-center justify-content-center text-center">
          <h1 class="text-white font-weight-bold">Mentions légales</h1>
        </div>
      </div>
  </header>

  <!-- Mentions légales -->
  <section id="mentions-legales">
      <div class="container">
        <div class="row py-5 justify-content-center">
          <div class="col-md-8">
              <ul>
                <li>Créé avec <a href="https://www.djangoproject.com/" target="_blank">Django Framework</a></li>
                <li>Front-end template de <a href="https://startbootstrap.com/themes/creative/" target="_blank">Start Bootstrap</a></li>
                <li>Données issues de <a href="https://fr.openfoodfacts.org" target="_blank">OpenFoodFacts</a></li>
              </ul>
          </div>
        </div>
      </div>
  </section>
{% endblock content %}