Project/ProjectSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePageViewIndex

urlpatterns = [
    path('dashboard/', include('console_admin.urls', namespace='admin')),
    path('auth/', include('authentication.urls')),
    path('folio/', include('portfolio.urls')),
    path('', HomePageViewIndex.as_view(), name='index'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Project/console_admin/urls.py
from django.urls import path
from .views import customer, parameters,product, portfolio
from order.views import (HomepageView, OrderUpdateView, CreateOrderView, delete_order,
                         done_order_view, OrderUpdateHeader,
                         add_product, modify_order_item,  order_action_view
                         )

app_name = 'console_admin'
urlpatterns = [
    path('', HomepageView.as_view(), name='console_admin'),

    # Customers
    path('list_customer', customer.list_customer, name='list_customer'),
    path('create_customer/', customer.customer, name="create_customer"),
    path('update_customer/<str:pk>/', customer.customer, name="update_customer"),
    path('delete_customer/<str:pk>/', customer.delete_customer,
         name="delete_customer"),

    # Parameters
    path('list_parameters/', parameters.list_parameters, name="list_parameters"),
    path('create_parameters/', parameters.parameters, name="create_parameters"),
    path('update_parameters/<str:pk>/', parameters.parameters, name="update_parameters"),
    path('delete_parameters/<str:pk>/', parameters.delete_parameters, name="delete_parameters"),


    # Portfolio
    path('list_portfolio/', portfolio.list_portfolio, name="list_portfolio"),
    path('create_portfolio/', portfolio.create_portfolio, name="create_portfolio"),
    path('update_portfolio/<str:pk>/', portfolio.update_portfolio,
         name="update_portfolio"),
    path('delete_portfolio/<str:pk>/', portfolio.delete_portfolio,
         name="delete_portfolio"),

    # Category
    path('categories-list/', product.CategoriesListView.as_view(), name='categories_list'),
    path('categories-create/', product.CreateCategoriesView.as_view(), name='categories_create'),
    path('categories-update/<int:pk>/', product.CategoryUpdateView.as_view(), name='categories_update'),
    path('categories-delete/<int:pk>/', product.delete_category, name='categories_delete'),

    # Product
    path('product-list/', product.ProductListView.as_view(), name='product_list'),
    path('product-create/', product.CreateProductView.as_view(), name='product_create'),
    path('product-update/<int:pk>/', product.ProductUpdateView.as_view(), name='product_update'),
    path('product-delete/<int:pk>/', product.delete_product, name='product_delete'),

    # order
    path('create/', CreateOrderView.as_view(), name='create_order'),
    path('update-order/<int:pk>/', OrderUpdateHeader.as_view(), name='update_order_header'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='update_order'),
    path('done/<int:pk>/', done_order_view, name='done_order'),
    path('delete/<int:pk>/', delete_order, name='delete_order'),
    path('action/<int:pk>/<slug:action>/', order_action_view, name='order_action'),
    path('add-product/<int:pk>/<int:dk>/',add_product, name='add_product'),
    path('modify-order-item/<int:orderid>/<int:pk>/<slug:action>', modify_order_item, name='modify_order_item'),

]

Project/portfolio/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


app_name = 'portfolio'
urlpatterns = [
    path('all/', views.allportfolio,name='all'),
    path("detail/<int:pk>/", views.detailportfolio,name='detail'),
]

Project/authentication/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

from django.db import models
from django.utils.translation import ugettext_lazy as _


class MyUserManager(BaseUserManager):
    """
    A custom user manager to deal with emails as unique identifiers for auth
    instead of usernames. The default that's used is "UserManager"
    """

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, password, **extra_fields)


class Account(AbstractBaseUser, PermissionsMixin):
    """Custom User model definition for email identification use."""
    email = models.EmailField(unique=True, null=True)
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return str(self.id) + ' - ' + self.first_name + ' ' + self.last_name

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    class Meta:
        verbose_name = 'Email', 'first_name'


class Address(models.Model):
    users = models.ForeignKey(Account, on_delete=models.CASCADE)
    address = models.CharField(_('address'), max_length=50)
    address2 = models.CharField(_('address more'), max_length=50, blank=True)
    zipcode = models.CharField(_('zipcode'), max_length=5)
    city = models.CharField(_('city'), max_length=60)
    country = models.CharField(_('country'), max_length=50)
    phone1 = models.CharField(_('mobile'), max_length=15, blank=True)
    phone2 = models.CharField(_('fix'), max_length=15, blank=True)
    delivery_address = models.BooleanField(_('address delivery'), default=False)

    class Meta:
        verbose_name = 'Address'
        verbose_name_plural = 'Address'
        unique_together = (('users', 'delivery_address'),)
        indexes = [
            models.Index(fields=['users', 'delivery_address']),
        ]

    def __str__(self):
        return self.address

Project/console_admin/forms/account.py
from django.forms import ModelForm
from authentication.models import Account, Address


class AccountForm(ModelForm):
    class Meta:
        model = Account
        fields = (
            'last_name',
            'first_name',
            'email'
        )


class AddressForm(ModelForm):
    class Meta:
        model = Address
        fields = (
            'address',
            'address2',
            'zipcode',
            'city',
            'country',
            'phone1',
            'phone2'
        )

Project/console_admin/forms/parameters.py
from django.forms import ModelForm
from console_admin.models import Parameters


class ParametersForm(ModelForm):
    class Meta:
        model = Parameters
        fields = ('keyfield',
                  'keydescription',
                  'charfield',
                  'textfield',
                  'decimalfield',
                  'intergerfield',
                  'booleanfield',
                  'imagefield')

Project/console_admin/forms/portfolio.py
from django.forms import ModelForm
from portfolio.models import Portfolio


class PortfolioForm(ModelForm):
    class Meta:
        model = Portfolio
        fields = '__all__'

Project/portfolio/forms.py
from django import forms
from django.forms import ModelForm

from .models import Portfolio


class PortfolioForm(ModelForm):
    class Meta:
        model = Portfolio
        fields = '__all__'

Project/console_admin/views/customer.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.core.mail import send_mail

from authentication.models import Account, Address
from console_admin.forms.account import AccountForm, AddressForm
from order.models import Order

"""
    List, create, update, delete customer and address
"""


@staff_member_required()
@login_required(login_url="index")
def list_customer(request):
    """List customer"""
    customers = Account.objects.filter(is_staff=False).order_by('id')
    count_customers = Account.objects.filter(is_staff=False).count()
    return render(request, 'console_admin/customer_list.html', locals())


@staff_member_required()
@login_required(login_url="index")
def customer(request, pk=None):
    " Create or Update customer"
    inst_user = Account.objects.get(id=pk) if pk is not None else None
    inst_address_billing = Address.objects.filter(users_id=pk) if pk is not None else None

    if request.method == "GET":
        account_form = AccountForm(instance=inst_user)
        address_form = AddressForm(instance=inst_address_billing)

        return render(request, 'console_admin/customer_form.html', locals())
    else:
        account_form = AccountForm(request.POST, request.FILES, instance=inst_user)
        address_form = AddressForm(request.POST, request.FILES, instance=inst_address_billing)

        if account_form.is_valid() and address_form.is_valid():

            if pk is not None:
                account_form.save()
                address_form.save()
            else:
                my_password = Account.objects.make_random_password()
                account = account_form.save(commit=False)
                account.set_password(my_password)
                account.save()

                address = address_form.save(commit=False)

                # Assign Account to Address billing
                address.users = account
                address.save()

                # Send an email to the user with the token:
                mail_subject: str = '[Sandrine Chevalier] Votre compte'
                to_email: str = account.email
                context = {'account': account, 'passwd': my_password}
                msg_plain = render_to_string(
                    'console_admin/mail/account_create_update_passwd.txt',
                    context)
                msg_html = render_to_string(
                    'console_admin/mail/account_create_update_passwd.html',
                    context)
                send_mail(
                    mail_subject,
                    msg_plain,
                    'sc@gmail.com',
                    [to_email],
                    html_message=msg_html,
                )
            return redirect('console_admin:list_customer')


@staff_member_required()
@login_required(login_url="index")
def delete_customer(request, pk):
    """ Delete account customer with the check question """
    custom = Account.objects.get(id=pk)
    address = Address.objects.filter(users_id=pk)
    nborder = Order.objects.filter(customer_id=pk).count()

    if request.method == "POST":
        custom.delete()
        address.delete()
        return redirect('console_admin:list_customer')

    if nborder == 0:
        context = {'item': customer}
        return render(request, 'console_admin/delete.html', context)
    else:
        context = {'item': customer,
                   'message': 'Impossible de supprimer car commande en cours'
                   }
        return render(request, 'console_admin/delete.html', context)

Project/console_admin/views/parameters.py
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.shortcuts import render

from console_admin.forms.parameters import ParametersForm
from console_admin.models import Parameters
from authentication.models import Account
from order.models import Order


@staff_member_required()
@login_required(login_url="index")
def list_parameters(request):
    """ list Parameters """
    params = Parameters.objects.all()
    return render(request, 'console_admin/parameters_list.html', locals())


@staff_member_required()
@login_required(login_url="index")
def parameters(request, pk=None):
    """ Creaate or Update Parameters"""
    if pk is None:
        # Create Parameters
        if request.method == "POST":
            param_form = ParametersForm(request.POST)
            param_form.fields['keyfield'].widget.attrs['readonly'] = True
            if param_form.is_valid():
                params = param_form.save()
                params.save()
                return redirect('console_admin:list_parameters')
        else:
            param_form = ParametersForm()
            param_form.fields['keyfield'].widget.attrs['readonly'] = True

        return render(request, 'console_admin/parameters_form.html',
                      {'param_form': param_form})
    else:
        # Update Parameters
        params = Parameters.objects.get(id=pk)
        param_form = ParametersForm(instance=params)

        if request.method == "POST":
            param_form = ParametersForm(request.POST, request.FILES,
                                        instance=params)
            if param_form.is_valid():
                param_form.save()
                return redirect('console_admin:list_parameters')

        context = {
            'param_form': param_form}

        return render(request, 'console_admin/parameters_form.html', context)


@staff_member_required()
@login_required(login_url="index")
def delete_parameters(request, pk=None):
    """ Delete parameters with the check question """
    params = Parameters.objects.get(id=pk)
    if request.method == "POST":
        params.delete()
        return redirect('console_admin:list_parameters')
    context = {'item': params}
    return render(request, 'console_admin/delete.html', context)

Project/console_admin/views/portfolio.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from portfolio.models import Portfolio
from portfolio.forms import PortfolioForm


@staff_member_required()
@login_required(login_url="index")
def list_portfolio(request):
    """ List porfolio"""
    portfolios = Portfolio.objects.all()
    return render(request, 'console_admin/portfolio_list.html', locals())


@staff_member_required()
@login_required(login_url="index")
def create_portfolio(request):
    """ Create porfolio"""
    form = PortfolioForm()

    if request.method == "POST":
        form = PortfolioForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('console_admin:list_portfolio')

    context = {'form': form}
    return render(request, 'console_admin/portfolio_form.html', context)


@staff_member_required()
@login_required(login_url="index")
def update_portfolio(request, pk):
    """ Update porfolio"""
    portfolio = Portfolio.objects.get(id=pk)
    form = PortfolioForm(instance=portfolio)

    if request.method == "POST":
        form = PortfolioForm(request.POST, request.FILES, instance=portfolio)
        if form.is_valid():
            form.save()
        return redirect('console_admin:list_portfolio')

    context = {'form': form}
    return render(request, 'console_admin/portfolio_form.html', context)


@staff_member_required()
@login_required(login_url="index")
def delete_portfolio(request, pk):
    """ Delete portfolio with the check question """
    portfolio = Portfolio.objects.get(id=pk)

    if request.method == "POST":
        portfolio.delete()
        return redirect('console_admin:list_portfolio')

    context = {'item': portfolio}
    return render(request, 'console_admin/delete.html', context)

Project/portfolio/views.py
from .models import Portfolio
from console_admin.models import Parameters
from django.shortcuts import render


# # Create your views here.
def allportfolio(request):
    # query the db to return all projects objects
    portfolios = Portfolio.objects.all()
    context = {'portfolios': portfolios}
    params = Parameters.objects.all()

    for param in params:
        if param.keyfield == 'logo_societe':
            context['logo'] = param.imagefield
        if param.keyfield == 'tel_societe':
            context['tel_societe'] = param.charfield
    return render(request, 'portfolio/list.html', context)


def detailportfolio(request, pk):
    portfolios = Portfolio.objects.get(id=pk)
    context = {'portfolios': portfolios}
    params = Parameters.objects.all()
    for param in params:
        if param.keyfield == 'logo_societe':
            context['logo'] = param.imagefield
        if param.keyfield == 'tel_societe':
            context['tel_societe'] = param.charfield

    return render(request, 'portfolio/detail.html', context)

Project/console_admin/templates/console_admin/customer_form.html
{% extends "baseadmin.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
     <!-- Etat List customers -->
      <div class="row">
        <div class="col-lg-12">
            <div class="portlet-box portlet-fullHeight mb-30">
                <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                    <div class="flex d-flex flex-column">
                        {% if customer != empty %}
                            <h3>Code Client : <b>{{customer}}</b></h3><br>
                        {%  else %}
                            <h3>Client</h3><br>
                        {% endif %}

                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ account_form|crispy }}<br>
                            <table  border="1">
                                <tr>
                                    <td><h3>Address Client</h3></td>

                                </tr>

                                <tr>
                                    <td >{{ address_form|crispy }}</td>

                                </tr>
                            </table>
                            <br>
                            <input class="btn btn-icon-right btn-primary" type="submit" value="Enregistrer">


                        </form>
                    </div>
                </div>
            </div>
        </div>
      </div>


{% endblock %}

Project/console_admin/templates/console_admin/customer_list.html
{% extends "baseadmin.html" %}

{% load static %}

{% block content %}
    <div class="page-content">
        <div class="container-fluid">
            <div class="row align-items-center mb-30 pt-30">
                <div class="col-md-12 mr-auto ml-auto">
                    <div class="mb-0">
                        <!-- Etat Clients Documents -->
                          <div class="row">
                            <div class="col-lg-12">
                                <div class="portlet-box portlet-fullHeight mb-30">
                                    <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                                        <div class="flex d-flex flex-column">
                                            <h3>Liste des Clients ({{ count_customers }})</h3>
                                        </div>

                                    </div>
                                    <br>
                                    <a class="btn btn-primary" href="{% url 'console_admin:create_customer' %}">
                                        <span class="nav-text">
                                            Créer un Client
                                        </span>
                                    </a>
                                    <br>
                                    <br>
                                    <div class="portlet-body no-padding">
                                        <div class="table-responsive">
                                            <table class="table mb-0">
                                                <thead>
                                                    <tr>
                                                        <th><p class="text-center">Code Client<p></th>
                                                        <th>Nom Prenom</th>
                                                        <th>Email</th>
                                                        <th>Derniere Connection</th>
                                                        <th>Accès</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                   {% for customer in customers %}
                                                     <tr>
                                                         <td><p class="text-center">{{ customer.id}}</p></td>
                                                        <td>
                                                             <span>{{ customer.first_name }} {{ customer.last_name }} </span>
                                                        </td>
                                                        <td>
                                                            <span>{{ customer.email }}</span>
                                                        <td>
                                                            <span>{{ customer.last_login }}</span>
                                                        </td>
                                                        <td>

                                                            <a href="{% url 'console_admin:update_customer' customer.id %}" class="btn-icon-o btn-primary radius100 btn-icon-sm mr-2 mb-2">
                                                                <i class="fa fa-file"></i>
                                                            </a>
                                                            <a href="{% url 'console_admin:delete_customer' customer.id %}" class="btn-icon-o btn-danger radius100 btn-icon-sm mr-2 mb-2">
                                                                <i class="fa fa-trash"></i>
                                                            </a>
                                                        </td>
                                                    </tr>
                                                   {%  endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                          </div>
                    </div>
                </div>
            </div><!--portlet-->
        </div><!--col-->
    </div>
      <!-- End Etat Clients Documents -->











{% endblock content %}

Project/console_admin/templates/console_admin/delete.html
{% extends "baseadmin.html" %}

{% load static %}

{% block content %}
 <!-- Etat List customers -->
      <div class="row">
        <div class="col-lg-12">
            <div class="portlet-box portlet-fullHeight mb-30">
                <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                    <div class="flex d-flex flex-column">

                        {% if message == None %}
                            <form method="post" action="">
                              {% csrf_token %}
                              <p>Etes vous sur de vouloir supprimer {{ item }} ?</p>
                              <input class="btn btn-icon btn-danger" type="submit" value="Supprimer">
                            </form>
                        {%  else %}
                            <p class="alert-danger">{{ message }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
      </div>
{%  endblock %}

Project/console_admin/templates/console_admin/order_form.html
{% extends "baseadmin.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
     <!-- Etat List customers -->
      <div class="row">
        <div class="col-lg-12">
            <div class="portlet-box portlet-fullHeight mb-30">
                <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                    <div class="flex d-flex flex-column">

                        <h3>Commande : <b>{{ order.type_doc }}-{{ order.id }}</b></h3><br>

                        <span class="h5">{{ order.users.last_name|lower|capfirst}} {{ order.users.first_name|lower|capfirst}}</span>
                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ order_form|crispy }}<br>

                            <br>
                            <input class="btn btn-icon-right btn-primary" type="submit" value="Enregistrer">



                        </form>
                    </div>
                </div>
            </div>
        </div>
      </div>


{% endblock %}

Project/console_admin/templates/console_admin/portfolio_list.html
{% extends "baseadmin.html" %}

{% load static %}

{% block content %}
<div class="page-content">
    <div class="container-fluid">
        <div class="row align-items-center mb-30 pt-30">
            <div class="col-md-12 mr-auto ml-auto">
                <div class="mb-0">
                      <div class="row">
                        <div class="col-lg-12">
                            <div class="portlet-box portlet-fullHeight mb-30">
                                <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                                    <div class="flex d-flex flex-column">
                                        <h3>Liste des images </h3>
                                    </div>

                                </div>
                                <br>
                                <a class="btn btn-primary" href="{% url 'console_admin:create_portfolio' %}">
                                    <span class="nav-text">
                                        Créer une image Avant Apres
                                    </span>
                                </a>
                                <br>
                                <br>
                                <div class="portlet-body no-padding">

                                    <div class="table-responsive">
                                        <table class="table mb-0">
                                            <thead>
                                                <tr>
                                                    <th>Nom</th>
                                                    <th>Créé le</th>
                                                    <th>Avant</th>
                                                    <th>Après</th>
                                                    <th>Accès</th>

                                                </tr>
                                            </thead>
                                            <tbody>
                                               {% for portfolio in portfolios %}
                                                 <tr>
                                                    <td>
                                                        <span>{{ portfolio.id }} - {{ portfolio.title }}</span>
                                                    </td>
                                                    <td>
                                                        <span>{{ portfolio.date_lastupdate }} </span>
                                                    </td>
                                                    <td>
                                                        <span><img src=" {{ portfolio.img_before.url }}"  height="50" width="50" alt=""></span>
                                                    <td>
                                                        <span><img src=" {{ portfolio.img_after.url }}"  height="50" width="50" alt=""></span>
                                                    </td>
                                                    <td>

                                                        <a href="{% url 'console_admin:update_portfolio' portfolio.id %}" class="btn-icon-o btn-primary radius100 btn-icon-sm mr-2 mb-2">
                                                            <i class="fa fa-file"></i>
                                                        </a>
                                                        <a href="{% url 'console_admin:delete_portfolio' portfolio.id %}" class="btn-icon-o btn-danger radius100 btn-icon-sm mr-2 mb-2">
                                                            <i class="fa fa-trash"></i>
                                                        </a>

                                                    </td>
                                                </tr>

                                               {%  endfor %}

                                            </tbody>
                                        </table>


                                        {% for ligaddress in customers.address_set.all %}
                                            Nom : {{ ligaddress.name }}<br>
                                            {{ ligaddress.address }}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                      </div>
                </div>
            </div>
        </div><!--portlet-->
    </div><!--col-->
</div>
{% endblock content %}