Project/ProjectSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePageViewIndex

urlpatterns = [
    path('dashboard/', include('console_admin.urls', namespace='admin')),
    path('auth/', include('authentication.urls')),
    path('folio/', include('portfolio.urls')),
    path('', HomePageViewIndex.as_view(), name='index'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Project/portfolio/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


app_name = 'portfolio'
urlpatterns = [
    path('all/', views.allportfolio,name='all'),
    path("detail/<int:pk>/", views.detailportfolio,name='detail'),
]

Project/portfolio/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.
class Portfolio(models.Model):
    """Custom User model definition for portfolio."""
    title = models.CharField(_('title'), max_length=30, blank=True)
    description = models.TextField(_('description'), blank=True)
    date_lastupdate = models.DateTimeField(_('date'), auto_now=True)
    img_before = models.ImageField(upload_to='images/')
    img_after = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

Project/console_admin/forms/portfolio.py
from django.forms import ModelForm
from portfolio.models import Portfolio


class PortfolioForm(ModelForm):
    class Meta:
        model = Portfolio
        fields = '__all__'

Project/portfolio/forms.py
from django import forms
from django.forms import ModelForm

from .models import Portfolio


class PortfolioForm(ModelForm):
    class Meta:
        model = Portfolio
        fields = '__all__'

Project/console_admin/views/portfolio.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from portfolio.models import Portfolio
from portfolio.forms import PortfolioForm


@staff_member_required()
@login_required(login_url="index")
def list_portfolio(request):
    """ List porfolio"""
    portfolios = Portfolio.objects.all()
    return render(request, 'console_admin/portfolio_list.html', locals())


@staff_member_required()
@login_required(login_url="index")
def create_portfolio(request):
    """ Create porfolio"""
    form = PortfolioForm()

    if request.method == "POST":
        form = PortfolioForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('console_admin:list_portfolio')

    context = {'form': form}
    return render(request, 'console_admin/portfolio_form.html', context)


@staff_member_required()
@login_required(login_url="index")
def update_portfolio(request, pk):
    """ Update porfolio"""
    portfolio = Portfolio.objects.get(id=pk)
    form = PortfolioForm(instance=portfolio)

    if request.method == "POST":
        form = PortfolioForm(request.POST, request.FILES, instance=portfolio)
        if form.is_valid():
            form.save()
        return redirect('console_admin:list_portfolio')

    context = {'form': form}
    return render(request, 'console_admin/portfolio_form.html', context)


@staff_member_required()
@login_required(login_url="index")
def delete_portfolio(request, pk):
    """ Delete portfolio with the check question """
    portfolio = Portfolio.objects.get(id=pk)

    if request.method == "POST":
        portfolio.delete()
        return redirect('console_admin:list_portfolio')

    context = {'item': portfolio}
    return render(request, 'console_admin/delete.html', context)

Project/portfolio/views.py
from .models import Portfolio
from console_admin.models import Parameters
from django.shortcuts import render


# # Create your views here.
def allportfolio(request):
    # query the db to return all projects objects
    portfolios = Portfolio.objects.all()
    context = {'portfolios': portfolios}
    params = Parameters.objects.all()

    for param in params:
        if param.keyfield == 'logo_societe':
            context['logo'] = param.imagefield
        if param.keyfield == 'tel_societe':
            context['tel_societe'] = param.charfield
    return render(request, 'portfolio/list.html', context)


def detailportfolio(request, pk):
    portfolios = Portfolio.objects.get(id=pk)
    context = {'portfolios': portfolios}
    params = Parameters.objects.all()
    for param in params:
        if param.keyfield == 'logo_societe':
            context['logo'] = param.imagefield
        if param.keyfield == 'tel_societe':
            context['tel_societe'] = param.charfield

    return render(request, 'portfolio/detail.html', context)

Project/portfolio/templates/portfolio/detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="page-breadcrumb title-space-lg bg-parallax parallax-overlay" data-jarallax='{"speed": 0.2}' style='background-image: url("{% static 'images/bg2.jpg' %}")'>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'portfolio:all' %}">Retour</a></li>
                        <li class="breadcrumb-item">Portfolio Detail</li>
                    </ol>
                    <h1>{{ portfolios.title }}</h1>
                </div>
            </div>
        </div>
    </div><!--page title end-->

    <div class="container pt100 pb60">
        <div class="pt40">

                <div class="cbp-item web-design logos identity graphic">
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <div class="cbp-l-caption-title portfolio-title">
                                    {{ portfolios.title }}
                                 </div>

                            </div>
                        </div>
                    </div>

                    <div class="cbp-caption-defaultWrap">
                        <div class="images-work mt-2">
                            <div class="before m-3 ">
                                Avant
                                <img class="img-fluid card-img rounded mt-2" src=" {{ portfolios.img_before.url }}"  height="30%" width="30%" alt="">
                            </div>
                            <div class="after m-3">
                                 Après
                                <img class="img-fluid card-img rounded mt-2" src="{{ portfolios.img_after.url }}"  height="30%" width="30%"  alt="">
                            </div>
                        </div>
                        <h3>Descriptions</h3>
                        <h4>{{ portfolios.description }}<h4>
                    </div>

                </div>

         </div>
      </div>


{% endblock content %}

Project/portfolio/templates/portfolio/list.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="page-breadcrumb title-space-lg bg-parallax parallax-overlay" data-jarallax='{"speed": 0.2}' style='background-image: url("{% static 'images/bg2.jpg' %}")'>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'index' %}">Accueil</a></li>
                        <li class="breadcrumb-item">Portfolio</li>
                    </ol>
                </div>
            </div>
        </div>
    </div><!--page title end-->

    <div class="container pt100 pb60">
        <div class="pt40">
            {% for portfolio in portfolios %}
                <div class="cbp-item web-design logos identity graphic">
                    <div class="cbp-caption-activeWrap">
                        <div class="cbp-l-caption-alignLeft">
                            <div class="cbp-l-caption-body">
                                <div class="cbp-l-caption-title portfolio-title">
                                    {{ portfolio.title }}
                                 </div>
                            {% if portfolio.description != '' %}

                            <a href="{% url 'portfolio:detail' portfolio.id %}" >

                                <div class="text-md-right portfolio-descriptions ">
                                Voir le descriptif
                                </div>
                            </a>

                    {% endif %}
                            </div>
                        </div>
                    </div>

                    <div class="cbp-caption-defaultWrap">
                        <div class="images-work mt-2">
                            <div class="before m-3 ">
                                Avant
                                <img class="img-fluid card-img rounded mt-2" src=" {{ portfolio.img_before.url }}"  height="30%" width="30%" alt="">
                            </div>
                            <div class="after m-3">
                                 Après
                                <img class="img-fluid card-img rounded mt-2" src="{{ portfolio.img_after.url }}"  height="30%" width="30%"  alt="">
                            </div>
                        </div>
                    </div>

                </div>
            {% endfor %}
         </div>
      </div>

{% endblock content %}