Project/ProjectSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from .views import HomePageViewIndex

urlpatterns = [
    path('dashboard/', include('console_admin.urls', namespace='admin')),
    path('auth/', include('authentication.urls')),
    path('folio/', include('portfolio.urls')),
    path('', HomePageViewIndex.as_view(), name='index'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Project/console_admin/urls.py
from django.urls import path
from .views import customer, parameters,product, portfolio
from order.views import (HomepageView, OrderUpdateView, CreateOrderView, delete_order,
                         done_order_view, OrderUpdateHeader,
                         add_product, modify_order_item,  order_action_view
                         )

app_name = 'console_admin'
urlpatterns = [
    path('', HomepageView.as_view(), name='console_admin'),

    # Customers
    path('list_customer', customer.list_customer, name='list_customer'),
    path('create_customer/', customer.customer, name="create_customer"),
    path('update_customer/<str:pk>/', customer.customer, name="update_customer"),
    path('delete_customer/<str:pk>/', customer.delete_customer,
         name="delete_customer"),

    # Parameters
    path('list_parameters/', parameters.list_parameters, name="list_parameters"),
    path('create_parameters/', parameters.parameters, name="create_parameters"),
    path('update_parameters/<str:pk>/', parameters.parameters, name="update_parameters"),
    path('delete_parameters/<str:pk>/', parameters.delete_parameters, name="delete_parameters"),


    # Portfolio
    path('list_portfolio/', portfolio.list_portfolio, name="list_portfolio"),
    path('create_portfolio/', portfolio.create_portfolio, name="create_portfolio"),
    path('update_portfolio/<str:pk>/', portfolio.update_portfolio,
         name="update_portfolio"),
    path('delete_portfolio/<str:pk>/', portfolio.delete_portfolio,
         name="delete_portfolio"),

    # Category
    path('categories-list/', product.CategoriesListView.as_view(), name='categories_list'),
    path('categories-create/', product.CreateCategoriesView.as_view(), name='categories_create'),
    path('categories-update/<int:pk>/', product.CategoryUpdateView.as_view(), name='categories_update'),
    path('categories-delete/<int:pk>/', product.delete_category, name='categories_delete'),

    # Product
    path('product-list/', product.ProductListView.as_view(), name='product_list'),
    path('product-create/', product.CreateProductView.as_view(), name='product_create'),
    path('product-update/<int:pk>/', product.ProductUpdateView.as_view(), name='product_update'),
    path('product-delete/<int:pk>/', product.delete_product, name='product_delete'),

    # order
    path('create/', CreateOrderView.as_view(), name='create_order'),
    path('update-order/<int:pk>/', OrderUpdateHeader.as_view(), name='update_order_header'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='update_order'),
    path('done/<int:pk>/', done_order_view, name='done_order'),
    path('delete/<int:pk>/', delete_order, name='delete_order'),
    path('action/<int:pk>/<slug:action>/', order_action_view, name='order_action'),
    path('add-product/<int:pk>/<int:dk>/',add_product, name='add_product'),
    path('modify-order-item/<int:orderid>/<int:pk>/<slug:action>', modify_order_item, name='modify_order_item'),

]

Project/portfolio/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


app_name = 'portfolio'
urlpatterns = [
    path('all/', views.allportfolio,name='all'),
    path("detail/<int:pk>/", views.detailportfolio,name='detail'),
]

Project/product/models.py
from django.db import models
from django.conf import settings
from .managers import ProductManager

CURRENCY = settings.CURRENCY


class Category(models.Model):
    title = models.CharField(max_length=150, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['id']

    def __str__(self):
        return self.title

    @staticmethod
    def filter_data(request, queryset):
        return queryset


class Product(models.Model):
    active = models.BooleanField(default=True)
    title = models.CharField(max_length=150, unique=True)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)
    value = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    discount_value = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    final_value = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    qty = models.PositiveIntegerField(default=1)

    objects = models.Manager()
    broswer = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'

    def save(self, *args, **kwargs):
        self.final_value = self.discount_value if self.discount_value > 0 else self.value
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def tag_final_value(self):
        return f'{self.final_value} {CURRENCY}'

    tag_final_value.short_description = 'Value'

    @staticmethod
    def filter_data(request, queryset):
        return queryset

Project/product/forms.py
from django import forms
from .models import Category, Product


class BaseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class CategoryCreateForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title']


class CategoryEditForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Category
        fields = ['title']


class ProductCreateForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title','category','qty','value','active']


class ProductEditForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title','category','qty','value','active']

Project/console_admin/views/product.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404, reverse
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView
from django.views.generic import ListView
from django_tables2 import RequestConfig

from product.forms import CategoryCreateForm, CategoryEditForm, ProductCreateForm, ProductEditForm
from product.models import Category, Product
from product.tables import CategoryTable, ProductTable


@method_decorator(staff_member_required, name='dispatch')
class CategoriesListView(ListView):
    """ List categories """
    template_name = 'product/categories_list.html'
    model = Category
    paginate_by = 50

    def get_queryset(self):
        qs = Category.objects.all()
        if self.request.GET:
            qs = Category.filter_data(self.request, qs)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = CategoryTable(self.object_list)
        RequestConfig(self.request).configure(category)
        context.update(locals())
        return context


@method_decorator(staff_member_required, name='dispatch')
class CreateCategoriesView(CreateView):
    """ Create categories """
    template_name = 'product/categories_create.html'
    form_class = CategoryCreateForm
    model = Category

    def get_success_url(self):
        self.new_object.refresh_from_db()
        return reverse('console_admin:categories_list')

    def form_valid(self, form):
        object = form.save()
        object.refresh_from_db()
        self.new_object = object
        return super().form_valid(form)


@method_decorator(staff_member_required, name='dispatch')
class CategoryUpdateView(UpdateView):
    """ Update categories """
    model = Category
    template_name = 'product/categories_update.html'
    form_class = CategoryEditForm

    def get_success_url(self):
        return reverse('console_admin:categories_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        instance = self.object
        qs_p = Category.objects.filter()[:12]
        category = CategoryTable(qs_p)
        RequestConfig(self.request).configure(category)
        context.update(locals())
        return context


@staff_member_required
def delete_category(request, pk):
    """ Delete categories """
    instance = get_object_or_404(Category, id=pk)
    instance.delete()
    messages.warning(request, 'La categorie a été supprimé')
    return redirect(reverse('console_admin:categories_list'))


# Product
@method_decorator(staff_member_required, name='dispatch')
class ProductListView(ListView):
    """ List categories """
    template_name = 'product/product_list.html'
    model = Product
    paginate_by = 50

    def get_queryset(self):
        qs = Product.objects.all()
        if self.request.GET:
            qs = Product.filter_data(self.request, qs)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = ProductTable(self.object_list)
        RequestConfig(self.request).configure(product)
        context.update(locals())
        return context


@method_decorator(staff_member_required, name='dispatch')
class CreateProductView(CreateView):
    template_name = 'product/product_create.html'
    form_class = ProductCreateForm
    model = Product

    def get_success_url(self):
        self.new_object.refresh_from_db()
        return reverse('console_admin:product_list')

    def form_valid(self, form):
        object = form.save()
        object.refresh_from_db()
        self.new_object = object
        return super().form_valid(form)


@method_decorator(staff_member_required, name='dispatch')
class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'product/product_update.html'
    form_class = ProductEditForm

    def get_success_url(self):
        return reverse('console_admin:product_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        instance = self.object
        qs_p = Product.objects.filter()[:12]
        product = ProductTable(qs_p)
        RequestConfig(self.request).configure(product)
        context.update(locals())
        return context


@staff_member_required
def delete_product(request, pk):
    instance = get_object_or_404(Product, id=pk)
    instance.delete()
    messages.warning(request, 'Le produit a été supprimé')
    return redirect(reverse('console_admin:product_list'))

Project/product/views.py
from django.shortcuts import render

# Create your views here.

Project/product/templates/product/categories_create.html
{% extends "baseadmin.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
     <!-- Etat List customers -->
      <div class="row">
        <div class="col-lg-12">
            <div class="portlet-box portlet-fullHeight mb-30">
                <p class="text-md-left"><h1>Categorie</h1></p>
                  <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                    <div class="flex d-flex flex-column">
                        <div class="portlet-body">
                             <form method="post" class="form-horizontal"> {% csrf_token %}
                                    <div class="card-body">
                                        {{ form }}
                                    </div>
                                    <div class="border-top">
                                        <div class="card-body">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </div>
                             </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>

{% endblock %}

Project/product/templates/product/categories_list.html
{% extends "baseadmin.html" %}
{% load render_table from django_tables2 %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="page-content">
        <div class="container-fluid">
            <div class="row align-items-center mb-30 pt-30">
                <div class="col-md-12 mr-auto ml-auto">
                    <div class="mb-0">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="portlet-box portlet-fullHeight mb-30">
                                    <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                                        <div class="flex d-flex flex-column">
                                            <h3>Liste des Catégories </h3>
                                        </div>
                                    </div>
                                    <br>
                                    <a class="btn btn-primary" href="{% url 'console_admin:categories_create' %}">
                                        <span class="nav-text">
                                            Créer une Catégorie
                                        </span>
                                    </a>
                                    <br>
                                    <br>
                                    <div class="portlet-body no-padding">
                                        <div class="table-responsive">
                                            <div class="comment-widgets scrollable">
                                                {% render_table category %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--portlet-->
        </div><!--col-->
    </div>
{% endblock content %}

Project/product/templates/product/categories_update.html
{% extends "baseadmin.html" %}
{% load render_table from django_tables2 %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
      <div class="row">
        <div class="col-lg-12">
            <div class="portlet-box portlet-fullHeight mb-30">
                <p class="text-md-left"><h1>Categorie</h1>
                <h4 class="page-title">{{ instance }}</h4></p>
                  <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                    <div class="flex d-flex flex-column">
                        <div class="page-wrapper">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="header">Edit</div>
                                        <div class="card-body">
                                            <form method="post" class="form">{% csrf_token %}
                                                {{ form }}
                                                <br>
                                                <button type="submit" class="btn btn-success">Save</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
            </div>
        </div>
      </div>



{% endblock %}

Project/product/templates/product/product_create.html
{% extends "baseadmin.html" %}

{% load static %}
{% load crispy_forms_tags %}
{% block content %}
     <!-- Etat List customers -->
      <div class="row">
        <div class="col-lg-12">
            <div class="portlet-box portlet-fullHeight mb-30">
                <p class="text-md-left"><h1>Produit</h1></p>
                  <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                    <div class="flex d-flex flex-column">
                        <div class="portlet-body">
                             <form method="post" class="form-horizontal"> {% csrf_token %}
                                    <div class="card-body">
                                        {{ form }}
                                    </div>
                                    <div class="border-top">
                                        <div class="card-body">
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </div>
                                    </div>
                             </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>

{% endblock %}

Project/product/templates/product/product_list.html
{% extends "baseadmin.html" %}
{% load render_table from django_tables2 %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="page-content">
        <div class="container-fluid">
            <div class="row align-items-center mb-30 pt-30">
                <div class="col-md-12 mr-auto ml-auto">
                    <div class="mb-0">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="portlet-box portlet-fullHeight mb-30">
                                    <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                                        <div class="flex d-flex flex-column">
                                            <h3>Liste des Produits </h3>
                                        </div>
                                    </div>
                                    <br>
                                    <a class="btn btn-primary" href="{% url 'console_admin:product_create' %}">
                                        <span class="nav-text">
                                            Créer un produit
                                        </span>
                                    </a>
                                    <br>
                                    <br>
                                    <div class="portlet-body no-padding">
                                        <div class="table-responsive">
                                            <div class="comment-widgets scrollable">
                                                {% render_table product %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!--portlet-->
        </div><!--col-->
    </div>
{% endblock content %}

Project/product/templates/product/product_update.html
{% extends "baseadmin.html" %}
{% load render_table from django_tables2 %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
      <div class="row">
        <div class="col-lg-12">
            <div class="portlet-box portlet-fullHeight mb-30">
                <p class="text-md-left"><h1>Produit</h1>
                <h4 class="page-title">{{ instance }}</h4></p>
                  <div class="portlet-header bg-light flex-row flex d-flex align-items-center">
                    <div class="flex d-flex flex-column">
                        <div class="page-wrapper">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="header">Edit</div>
                                        <div class="card-body">
                                            <form method="post" class="form">{% csrf_token %}
                                                {{ form }}
                                                <br>
                                                <button type="submit" class="btn btn-success">Save</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                  </div>
            </div>
        </div>
      </div>



{% endblock %}